### ISSUE TITLE
There is only caption_all.json in the dataset CUHK-PEDES, what are the train.json and test.json in the dataset part

### ISSUE THREAD

**Issue by SwimKY** [BrandonHanx/TextReID#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrandonHanx** [comment]
Please read README carefully before you make an issue :)
Please use the template to make your next issue :)
