### ISSUE TITLE
Cannot find test_query and train_query folders

### ISSUE THREAD

**Issue by liviust** [BrandonHanx/TextReID#4]
Hi @BrandonHanx 

In the ReadMe file, it is mentioned to setup the datasets dir as follows:

```datasets
└── cuhkpedes
    ├── annotations
    │   ├── test.json
    │   ├── train.json
    │   └── val.json
    ├── clip_vocab_vit.npy
    └── imgs
        ├── cam_a
        ├── cam_b
        ├── CUHK01
        ├── CUHK03
        ├── Market
        ├── test_query
        └── train_query
```
After downloading the cuhkpedes data set, we get only the imgs folder, containing cam_a, cam_b and CUHK01 folders. there is no test_query and train_query folders. Also, these folders are not in the repository. Could you provide more information regarding on these folders, more exactly, what kind of information they contain and how they must be set up?

Also, there are few more folders that are not part of the cuhkpedes, such as CUHK03 and Market. Do we need these data sets to reproduce the results?

Best regards,
liviust

**Comment by liviust** [comment]
> Hi, where did you get the CUHKPEDES dataset?
> 
> To me, the original dataset contains all these folders.

I have requested the data set from [Shuang Li](https://github.com/ShuangLI59/Person-Search-with-Natural-Language-Description).

**Comment by liviust** [comment]
> Hi, where did you get the CUHKPEDES dataset?
> 
> To me, the original dataset contains all these folders.

I have requested the data set from [Shuang Li](https://github.com/ShuangLI59/Person-Search-with-Natural-Language-Description).

**Comment by liviust** [comment]
> Hi, where did you get the CUHKPEDES dataset?
> 
> To me, the original dataset contains all these folders.

I have requested the data set from [Shuang Li](https://github.com/ShuangLI59/Person-Search-with-Natural-Language-Description).

**Comment by BrandonHanx** [comment]
Oops, that's weird...

I am sure the images in train_query and so on are needed.
You can see the caption example in the original CUHKPEDES README like this:
`[{"split": "train", "captions": ["A woman is wearing a gray shirt, a pair of brown pants and a pair of shoes.", "She is wearing a dark grey top and light colored pants."], "file_path": "train_query/p11600_s14885.jpg", "id": 11003}]`

Could you please have a check with her?

**Comment by liviust** [comment]
Found the issue. The db archive was corrupted. After fixing it, I managed to extract everything from it.

Thank you!

**Comment by changapple** [comment]
> 

May I ask, how do you fix the corrupted db archive? I met the same problem.
