### ISSUE TITLE
some problem in training and testing

### ISSUE THREAD

**Issue by ram7772** [BrandonHanx/TextReID#5]
Hello

I have some problem.
first: I don't find test_query and train_query file when I get images from [Dr. Shuang Li]
second: I have this problem for testing and training.

![image](https://user-images.githubusercontent.com/105381783/172700115-3538b265-2319-4850-bc2c-3f1a6a6744a4.png)

**Comment by BrandonHanx** [comment]
First question: please refer to https://github.com/BrandonHanx/TextReID/issues/4

Second question: it is seemingly not due to my code base, please check whether you put all files in the correct path

**Comment by ram7772** [comment]
Hi again 
I still have a problem.
I try the code on my laptop local and in google Colaboratory but I have the same problem.
![image](https://user-images.githubusercontent.com/105381783/172827485-7a27ebd7-ed31-4118-beb8-b89a597e8cfe.png)

**Comment by BrandonHanx** [comment]
Please double check that you put the json file in the correct path.

Note that it is not my responsibility to help you debug. :)

**Comment by ram7772** [comment]
Hello
when I run train.py file, it will train with all Cuhkpedes datasets.
can I manage it to use part of the Cuhkpedes dataset? 
Also, if I have a custom dataset what is the instruction I can use to make sure that I train with my custom dataset
Thank you
