### ISSUE TITLE
Problem about the clip_vocab_vit.npy

### ISSUE THREAD

**Issue by Frost-Yang-99** [BrandonHanx/TextReID#6]
Hi :)
I have a question about the pre-processing document clip_vocab_vit.npy. My understanding is that it contains the tensor of the CLIP-Text-Encoder output corresponding to each word (total 9408). My question is, the output dimension of CLIP-TEXT-ENCODER is 1024, but the tensor dimension of each word in clip_vocab_vit.npy is 512. Is there some other operation in it?
Thanks

**Comment by BrandonHanx** [comment]
Hi,

For ViT-based CLIP, after projection, the output dimension is 512.

**Comment by Frost-Yang-99** [comment]
Oh, I see, thank you
