### ISSUE TITLE
Research prepared to obtain a diploma degree in computer and Automation Engineering.

### ISSUE THREAD

**Issue by ram7772** [BrandonHanx/TextReID#7]
Hello!

My research focuses on Person search using Visual-Textual Attributes.
Having said that, I would like to use your model to assist me in my project, but I have some issues when I finish train and test the model.
My problem is trying to write code to run the model to get the same response as the photo. so Can you help me please!

![photo_2022-08-07_18-44-28](https://user-images.githubusercontent.com/105381783/183299249-dece8ac3-d6e4-4ecf-8555-f1bf221c402f.jpg)

**Comment by BrandonHanx** [comment]
Hi, please give more details to follow.

**Comment by ram7772** [comment]
![photo_2022-08-07_18-44-28](https://user-images.githubusercontent.com/105381783/183307685-d86ed3f8-691a-4625-b3cc-531a33740c76.jpg)

**Comment by ram7772** [comment]
I save the file inference_data.npz but I can't get the similarity variable to print it on the screen.

**Comment by ram7772** [comment]
![Screenshot 2022-08-07 223220](https://user-images.githubusercontent.com/105381783/183308008-4449d54a-9afe-43a9-866d-e19337cab6ea.jpg)

**Comment by ram7772** [comment]
Hello

I would like to do this

**Comment by BrandonHanx** [comment]
These images are drawn by these steps:
1. choose one sentence as the query
2. use this query to retrieve person images
3. rank the images according to the similarities

**Comment by luzhuflower** [comment]
请问有相关的代码帮助我参考吗，期待并感谢您的回复~~~


> 这些图像是通过以下步骤绘制的：
> 
> 1. 选择一个句子作为查询
> 2. 使用此查询检索人物图像
> 3. 根据相似性对图像进行排序
